# Generated by Django 3.2.9 on 2021-11-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('picture', models.CharField(max_length=250, verbose_name='Место хранения файла')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('parent_picture', models.IntegerField(blank=True, verbose_name='id оригинала')),
            ],
        ),
    ]
