# Generated by Django 3.2.9 on 2021-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent_picture',
            field=models.IntegerField(blank=True, null=True, verbose_name='id оригинала'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='Место хранения файла'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
    ]
