# Generated by Django 3.2.9 on 2021-11-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer_module', '0002_auto_20211110_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Место хранения файла'),
        ),
    ]
