# Generated by Django 3.2.9 on 2021-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer_module', '0003_alter_image_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Место хранения файла'),
        ),
    ]
